import type { GameTab } from '@/lib/game-types';

// Реальные сгенерированные иконки (Higgsfield, ретроспективно вытащены из истории аккаунта —
// см. обсуждение с пользователем) поверх эмодзи-заглушек. Пока покрыты вкладки навигации,
// валюты, титулы, питомцы и предметы (ITEMS, game-data.ts) — портреты рас/классов/боссов и
// локации заводятся отдельным приходом. Там, где картинки нет, компонент AssetIcon сам
// откатывается на эмодзи — ничего не ломается для непокрытых пока категорий.

export const TAB_ICON_IMAGES: Partial<Record<GameTab, string>> = {
  overview: '/images/nav/overview.webp',
  combat: '/images/nav/combat.webp',
  map: '/images/nav/map.webp',
  quests: '/images/nav/quests.webp',
  inventory: '/images/nav/inventory.webp',
  craft: '/images/nav/craft.webp',
  achievements: '/images/nav/achievements.webp',
  codex: '/images/nav/codex.webp',
  trophies: '/images/nav/trophies.webp',
  guild: '/images/nav/guild.webp',
  party: '/images/nav/party.webp',
  market: '/images/nav/market.webp',
  auction: '/images/nav/auction.webp',
  pvp: '/images/nav/pvp.webp',
  leaderboard: '/images/nav/leaderboard.webp',
  premium: '/images/nav/premium.webp',
  characters: '/images/nav/characters.webp',
  // 'weekly-challenge' — для этой вкладки иконка не генерировалась, остаётся эмодзи 🕯️.
};

export const CURRENCY_ICON_IMAGES: Record<string, string> = {
  gold: '/images/currency/gold.webp',
  crownShards: '/images/currency/crown_shards.webp',
  ash_shard: '/images/currency/ash_shard.webp',
  aylet_tear: '/images/currency/aylet_tear.webp',
  tornak_seal: '/images/currency/tornak_seal.webp',
  kessara_whisper: '/images/currency/kessara_whisper.webp',
  tempering_scroll: '/images/currency/tempering_scroll.webp',
};

// Ключи — Title.id (src/lib/social/titles.ts), все 16 титулов покрыты.
export const TITLE_ICON_IMAGES: Record<string, string> = {
  ashen_wanderer: '/images/titles/ashen_wanderer.webp',
  deep_veteran: '/images/titles/deep_veteran.webp',
  ashen_legend: '/images/titles/ashen_legend.webp',
  slayer: '/images/titles/slayer.webp',
  blood_harvest: '/images/titles/blood_harvest.webp',
  arena_champion: '/images/titles/arena_champion.webp',
  arena_elite: '/images/titles/arena_elite.webp',
  abyss_conqueror: '/images/titles/abyss_conqueror.webp',
  abyss_lord: '/images/titles/abyss_lord.webp',
  trophy_hunter: '/images/titles/trophy_hunter.webp',
  trophy_legend: '/images/titles/trophy_legend.webp',
  achievement_collector: '/images/titles/achievement_collector.webp',
  pet_master: '/images/titles/pet_master.webp',
  patron: '/images/titles/patron.webp',
  clan_chief: '/images/titles/clan_chief.webp',
  voice_of_karsus: '/images/titles/voice_of_karsus.webp',
};

// Ключи — Pet.id (src/lib/economy/pets.ts), все 12 питомцев покрыты.
export const PET_ICON_IMAGES: Record<string, string> = {
  ash_kitten: '/images/pets/ash_kitten.webp',
  rusty_crow: '/images/pets/rusty_crow.webp',
  root_sprite: '/images/pets/root_sprite.webp',
  ember_moth: '/images/pets/ember_moth.webp',
  void_hare: '/images/pets/void_hare.webp',
  bone_hound: '/images/pets/bone_hound.webp',
  kessara_owl: '/images/pets/kessara_owl.webp',
  molten_salamander: '/images/pets/molten_salamander.webp',
  ailet_fawn: '/images/pets/ailet_fawn.webp',
  tornak_golemling: '/images/pets/tornak_golemling.webp',
  karsus_wyrmling: '/images/pets/karsus_wyrmling.webp',
  cursed_shade_cub: '/images/pets/cursed_shade_cub.webp',
};

// Ключи — Item.id (src/lib/game-data.ts ITEMS), 88 из 94 предметов покрыты. Валютные Item-записи
// (ash_shard/aylet_tear/tornak_seal/kessara_whisper/tempering_scroll) сюда не входят — у них уже
// есть иконки в монетном стиле в CURRENCY_ICON_IMAGES, дублировать другим стилем не стали.
// Без иконки остаётся first_dragon_scale (для него отдельная генерация не производилась) — там
// AssetIcon откатывается на emoji, как и для любого непокрытого id.
export const ITEM_ICON_IMAGES: Record<string, string> = {
  ailet_pulsing_heart: '/images/items/ailet_pulsing_heart.webp',
  ailet_tear: '/images/items/ailet_tear.webp',
  amulet_vitality: '/images/items/amulet_vitality.webp',
  ancient_map: '/images/items/ancient_map.webp',
  antidote: '/images/items/antidote.webp',
  arcane_pendant: '/images/items/arcane_pendant.webp',
  ashen_amulet: '/images/items/ashen_amulet.webp',
  ashen_loyalty_fang: '/images/items/ashen_loyalty_fang.webp',
  blueprint_boots_fallen_pillar: '/images/items/blueprint_boots_fallen_pillar.webp',
  blueprint_crown_armor: '/images/items/blueprint_crown_armor.webp',
  blueprint_crown_fragment: '/images/items/blueprint_crown_fragment.webp',
  blueprint_crown_of_ash: '/images/items/blueprint_crown_of_ash.webp',
  blueprint_cursed_king_blade: '/images/items/blueprint_cursed_king_blade.webp',
  blueprint_gauntlets_broken_oath: '/images/items/blueprint_gauntlets_broken_oath.webp',
  boots_of_the_fallen_pillar: '/images/items/boots_of_the_fallen_pillar.webp',
  broken_oath_hammer: '/images/items/broken_oath_hammer.webp',
  celestial_robe: '/images/items/celestial_robe.webp',
  chainmail: '/images/items/chainmail.webp',
  cloth_sandals: '/images/items/cloth_sandals.webp',
  copper_ring: '/images/items/copper_ring.webp',
  crown_armor: '/images/items/crown_armor.webp',
  crown_fragment: '/images/items/crown_fragment.webp',
  crown_of_ash: '/images/items/crown_of_ash.webp',
  crown_shard: '/images/items/crown_shard.webp',
  cursed_king_blade: '/images/items/cursed_king_blade.webp',
  cursed_locket: '/images/items/cursed_locket.webp',
  dragon_scale: '/images/items/dragon_scale.webp',
  dragonscale_armor: '/images/items/dragonscale_armor.webp',
  dragonslayer: '/images/items/dragonslayer.webp',
  dwarven_greaves: '/images/items/dwarven_greaves.webp',
  dwarven_helm: '/images/items/dwarven_helm.webp',
  dwarven_plate: '/images/items/dwarven_plate.webp',
  echo_thorn_crown: '/images/items/echo_thorn_crown.webp',
  elixir_power: '/images/items/elixir_power.webp',
  elven_bow: '/images/items/elven_bow.webp',
  eternal_ember: '/images/items/eternal_ember.webp',
  first_fall_dust: '/images/items/first_fall_dust.webp',
  first_risen_crown: '/images/items/first_risen_crown.webp',
  flame_blade: '/images/items/flame_blade.webp',
  frost_axe: '/images/items/frost_axe.webp',
  gatekeeper_key: '/images/items/gatekeeper_key.webp',
  gauntlets_of_the_broken_oath: '/images/items/gauntlets_of_the_broken_oath.webp',
  greater_health: '/images/items/greater_health.webp',
  greaves_of_the_last_stand: '/images/items/greaves_of_the_last_stand.webp',
  grip_of_the_forgotten: '/images/items/grip_of_the_forgotten.webp',
  grumgar_fang: '/images/items/grumgar_fang.webp',
  health_potion: '/images/items/health_potion.webp',
  hunters_hood: '/images/items/hunters_hood.webp',
  ignira_fang: '/images/items/ignira_fang.webp',
  iron_cap: '/images/items/iron_cap.webp',
  iron_gauntlets: '/images/items/iron_gauntlets.webp',
  iron_ore: '/images/items/iron_ore.webp',
  iron_sword: '/images/items/iron_sword.webp',
  kessara_mirror_shard: '/images/items/kessara_mirror_shard.webp',
  kings_diadem: '/images/items/kings_diadem.webp',
  leather_armor: '/images/items/leather_armor.webp',
  leather_bracers: '/images/items/leather_bracers.webp',
  lucky_charm: '/images/items/lucky_charm.webp',
  mana_potion: '/images/items/mana_potion.webp',
  nimble_gloves: '/images/items/nimble_gloves.webp',
  oath_shield_shard: '/images/items/oath_shield_shard.webp',
  orcish_fists: '/images/items/orcish_fists.webp',
  petrified_law_shard: '/images/items/petrified_law_shard.webp',
  ring_of_focus: '/images/items/ring_of_focus.webp',
  ring_of_the_wild_hunt: '/images/items/ring_of_the_wild_hunt.webp',
  ring_power: '/images/items/ring_power.webp',
  ring_unquenchable_thirst: '/images/items/ring_unquenchable_thirst.webp',
  runed_vambraces: '/images/items/runed_vambraces.webp',
  rusty_sword: '/images/items/rusty_sword.webp',
  scholars_circlet: '/images/items/scholars_circlet.webp',
  scroll_fireball: '/images/items/scroll_fireball.webp',
  scroll_heal: '/images/items/scroll_heal.webp',
  shadow_cloak: '/images/items/shadow_cloak.webp',
  shadow_dagger: '/images/items/shadow_dagger.webp',
  shadow_essence: '/images/items/shadow_essence.webp',
  shadowstep_boots: '/images/items/shadowstep_boots.webp',
  steel_sword: '/images/items/steel_sword.webp',
  sturdy_greaves: '/images/items/sturdy_greaves.webp',
  swift_boots: '/images/items/swift_boots.webp',
  torn_hood: '/images/items/torn_hood.webp',
  traveling_boots: '/images/items/traveling_boots.webp',
  unborn_chieftain_seal: '/images/items/unborn_chieftain_seal.webp',
  void_crystal: '/images/items/void_crystal.webp',
  void_mask: '/images/items/void_mask.webp',
  void_staff: '/images/items/void_staff.webp',
  witness_eye: '/images/items/witness_eye.webp',
  wooden_talisman: '/images/items/wooden_talisman.webp',
  worn_gloves: '/images/items/worn_gloves.webp',
};

// Портреты рас (Race.slug) — все 6 покрыты. Большие painterly-арты (896×1200 исходник, 480px
// webp), не путать с ITEM/TAB/CURRENCY-иконками выше — те специально мелкие и плоские
// ("minimal iconic shape"), портреты — детальные картины для крупного показа (создание
// персонажа, боевой экран), не для мелких инлайн-иконок.
export const RACE_PORTRAIT_IMAGES: Record<string, string> = {
  dragonborn: '/images/portraits/races/dragonborn.webp',
  dwarves: '/images/portraits/races/dwarves.webp',
  elves: '/images/portraits/races/elves.webp',
  humans: '/images/portraits/races/humans.webp',
  orcs: '/images/portraits/races/orcs.webp',
  undead: '/images/portraits/races/undead.webp',
};

// Портреты классов (GameClass.slug), базовая форма (стадия 1) — все 26 покрыты. Эволюционные
// портреты (стадии 2-3, ~50 сгенерировано) сюда не входят — отдельный заход.
export const CLASS_PORTRAIT_IMAGES: Record<string, string> = {
  'ash-gladiator': '/images/portraits/classes/ash-gladiator.webp',
  'blood-hunter': '/images/portraits/classes/blood-hunter.webp',
  'bond-breaker': '/images/portraits/classes/bond-breaker.webp',
  'bone-guardian': '/images/portraits/classes/bone-guardian.webp',
  collapser: '/images/portraits/classes/collapser.webp',
  'decay-alchemist': '/images/portraits/classes/decay-alchemist.webp',
  'flame-legate': '/images/portraits/classes/flame-legate.webp',
  'frenzied-berserker': '/images/portraits/classes/frenzied-berserker.webp',
  'grave-smith': '/images/portraits/classes/grave-smith.webp',
  'heat-eater': '/images/portraits/classes/heat-eater.webp',
  'horde-leader': '/images/portraits/classes/horde-leader.webp',
  'moon-archer': '/images/portraits/classes/moon-archer.webp',
  oathkeeper: '/images/portraits/classes/oathkeeper.webp',
  'obsidian-warrior': '/images/portraits/classes/obsidian-warrior.webp',
  paladin: '/images/portraits/classes/paladin.webp',
  'plague-reaper': '/images/portraits/classes/plague-reaper.webp',
  priest: '/images/portraits/classes/priest.webp',
  ranger: '/images/portraits/classes/ranger.webp',
  rogue: '/images/portraits/classes/rogue.webp',
  'rune-reaper': '/images/portraits/classes/rune-reaper.webp',
  sorcerer: '/images/portraits/classes/sorcerer.webp',
  stoneskin: '/images/portraits/classes/stoneskin.webp',
  'thread-keeper': '/images/portraits/classes/thread-keeper.webp',
  'void-thief': '/images/portraits/classes/void-thief.webp',
  'wall-keeper': '/images/portraits/classes/wall-keeper.webp',
  warrior: '/images/portraits/classes/warrior.webp',
};

// Портреты боссов (Enemy.id, isBoss: true) — все 12 покрыты.
export const BOSS_PORTRAIT_IMAGES: Record<string, string> = {
  broken_oath: '/images/portraits/bosses/broken_oath.webp',
  echo_of_ailet: '/images/portraits/bosses/echo_of_ailet.webp',
  first_dragon: '/images/portraits/bosses/first_dragon.webp',
  first_risen: '/images/portraits/bosses/first_risen.webp',
  first_witness: '/images/portraits/bosses/first_witness.webp',
  flame_of_velarion: '/images/portraits/bosses/flame_of_velarion.webp',
  gatekeeper_of_the_deep: '/images/portraits/bosses/gatekeeper_of_the_deep.webp',
  grumgar_unborn: '/images/portraits/bosses/grumgar_unborn.webp',
  heart_of_ailet: '/images/portraits/bosses/heart_of_ailet.webp',
  keeper_of_ashes: '/images/portraits/bosses/keeper_of_ashes.webp',
  mirror_of_kessara: '/images/portraits/bosses/mirror_of_kessara.webp',
  statue_of_tornak: '/images/portraits/bosses/statue_of_tornak.webp',
};

// Иллюстрации локаций (Location.id, game-data.ts LOCATIONS) — 37 из 37 покрыты. Ландшафтные
// сцены (16:9 исходник, 640px webp), отдельный стиль от портретов персонажей выше.
export const LOCATION_IMAGES: Record<string, string> = {
  abyss_maw: '/images/locations/abyss_maw.webp',
  abyss_root: '/images/locations/abyss_root.webp',
  ashen_fortress: '/images/locations/ashen_fortress.webp',
  ashen_wasteland: '/images/locations/ashen_wasteland.webp',
  blood_arena: '/images/locations/blood_arena.webp',
  bone_cathedral: '/images/locations/bone_cathedral.webp',
  borderlands: '/images/locations/borderlands.webp',
  burned_village: '/images/locations/burned_village.webp',
  dead_shore: '/images/locations/dead_shore.webp',
  dragon_nests: '/images/locations/dragon_nests.webp',
  flame_cradle: '/images/locations/flame_cradle.webp',
  foundation_rift: '/images/locations/foundation_rift.webp',
  great_forge: '/images/locations/great_forge.webp',
  grumgar_fortress: '/images/locations/grumgar_fortress.webp',
  heart_of_grove: '/images/locations/heart_of_grove.webp',
  ignira_maw: '/images/locations/ignira_maw.webp',
  karsus_rift: '/images/locations/karsus_rift.webp',
  madness_forge: '/images/locations/madness_forge.webp',
  market: '/images/locations/market.webp',
  oath_hall: '/images/locations/oath_hall.webp',
  obsidian_labyrinth: '/images/locations/obsidian_labyrinth.webp',
  outer_grove: '/images/locations/outer_grove.webp',
  outer_marshes: '/images/locations/outer_marshes.webp',
  outer_mines: '/images/locations/outer_mines.webp',
  petrified_law: '/images/locations/petrified_law.webp',
  plague_camp: '/images/locations/plague_camp.webp',
  plague_gate: '/images/locations/plague_gate.webp',
  root_abyss: '/images/locations/root_abyss.webp',
  rune_workshop: '/images/locations/rune_workshop.webp',
  shade_mycelium: '/images/locations/shade_mycelium.webp',
  shipwreck_graveyard: '/images/locations/shipwreck_graveyard.webp',
  silent_halls: '/images/locations/silent_halls.webp',
  skull_trail: '/images/locations/skull_trail.webp',
  sorrow_road: '/images/locations/sorrow_road.webp',
  town: '/images/locations/town.webp',
  upper_deep: '/images/locations/upper_deep.webp',
  velarion_temple: '/images/locations/velarion_temple.webp',
};

// Ключи — `${GameClass.slug}:${stage}` для stage 2/3 (эволюционные формы, см.
// stageUnlockLevel/getEvolvedStage в character-portrait.ts) — 26 из 26 классов покрыты (52 файла).
// Базовая форма (stage 1) — см. CLASS_PORTRAIT_IMAGES выше.
export const CLASS_STAGE_PORTRAIT_IMAGES: Record<string, string> = {
  'ash-gladiator:2': '/images/portraits/stages/ash-gladiator_2.webp',
  'ash-gladiator:3': '/images/portraits/stages/ash-gladiator_3.webp',
  'blood-hunter:2': '/images/portraits/stages/blood-hunter_2.webp',
  'blood-hunter:3': '/images/portraits/stages/blood-hunter_3.webp',
  'bond-breaker:2': '/images/portraits/stages/bond-breaker_2.webp',
  'bond-breaker:3': '/images/portraits/stages/bond-breaker_3.webp',
  'bone-guardian:2': '/images/portraits/stages/bone-guardian_2.webp',
  'bone-guardian:3': '/images/portraits/stages/bone-guardian_3.webp',
  'collapser:2': '/images/portraits/stages/collapser_2.webp',
  'collapser:3': '/images/portraits/stages/collapser_3.webp',
  'decay-alchemist:2': '/images/portraits/stages/decay-alchemist_2.webp',
  'decay-alchemist:3': '/images/portraits/stages/decay-alchemist_3.webp',
  'flame-legate:2': '/images/portraits/stages/flame-legate_2.webp',
  'flame-legate:3': '/images/portraits/stages/flame-legate_3.webp',
  'frenzied-berserker:2': '/images/portraits/stages/frenzied-berserker_2.webp',
  'frenzied-berserker:3': '/images/portraits/stages/frenzied-berserker_3.webp',
  'grave-smith:2': '/images/portraits/stages/grave-smith_2.webp',
  'grave-smith:3': '/images/portraits/stages/grave-smith_3.webp',
  'heat-eater:2': '/images/portraits/stages/heat-eater_2.webp',
  'heat-eater:3': '/images/portraits/stages/heat-eater_3.webp',
  'horde-leader:2': '/images/portraits/stages/horde-leader_2.webp',
  'horde-leader:3': '/images/portraits/stages/horde-leader_3.webp',
  'moon-archer:2': '/images/portraits/stages/moon-archer_2.webp',
  'moon-archer:3': '/images/portraits/stages/moon-archer_3.webp',
  'oathkeeper:2': '/images/portraits/stages/oathkeeper_2.webp',
  'oathkeeper:3': '/images/portraits/stages/oathkeeper_3.webp',
  'obsidian-warrior:2': '/images/portraits/stages/obsidian-warrior_2.webp',
  'obsidian-warrior:3': '/images/portraits/stages/obsidian-warrior_3.webp',
  'paladin:2': '/images/portraits/stages/paladin_2.webp',
  'paladin:3': '/images/portraits/stages/paladin_3.webp',
  'plague-reaper:2': '/images/portraits/stages/plague-reaper_2.webp',
  'plague-reaper:3': '/images/portraits/stages/plague-reaper_3.webp',
  'priest:2': '/images/portraits/stages/priest_2.webp',
  'priest:3': '/images/portraits/stages/priest_3.webp',
  'ranger:2': '/images/portraits/stages/ranger_2.webp',
  'ranger:3': '/images/portraits/stages/ranger_3.webp',
  'rogue:2': '/images/portraits/stages/rogue_2.webp',
  'rogue:3': '/images/portraits/stages/rogue_3.webp',
  'rune-reaper:2': '/images/portraits/stages/rune-reaper_2.webp',
  'rune-reaper:3': '/images/portraits/stages/rune-reaper_3.webp',
  'sorcerer:2': '/images/portraits/stages/sorcerer_2.webp',
  'sorcerer:3': '/images/portraits/stages/sorcerer_3.webp',
  'stoneskin:2': '/images/portraits/stages/stoneskin_2.webp',
  'stoneskin:3': '/images/portraits/stages/stoneskin_3.webp',
  'thread-keeper:2': '/images/portraits/stages/thread-keeper_2.webp',
  'thread-keeper:3': '/images/portraits/stages/thread-keeper_3.webp',
  'void-thief:2': '/images/portraits/stages/void-thief_2.webp',
  'void-thief:3': '/images/portraits/stages/void-thief_3.webp',
  'wall-keeper:2': '/images/portraits/stages/wall-keeper_2.webp',
  'wall-keeper:3': '/images/portraits/stages/wall-keeper_3.webp',
  'warrior:2': '/images/portraits/stages/warrior_2.webp',
  'warrior:3': '/images/portraits/stages/warrior_3.webp',
};

// Спрайты обычных (не-босс) врагов из ENEMIES (game-data.ts) — 85/85, включая двух,
// названия которых в промптах Higgsfield отличаются формой прилагательного от game-data
// (feral_hatchling, mutated_root_horror) — сопоставлены вручную.
export const ENEMY_ICON_IMAGES: Record<string, string> = {
  abyss_maw_horror: '/images/enemies/abyss_maw_horror.webp',
  arena_champion: '/images/enemies/arena_champion.webp',
  arena_slave: '/images/enemies/arena_slave.webp',
  ash_marauder: '/images/enemies/ash_marauder.webp',
  ash_wyrmling: '/images/enemies/ash_wyrmling.webp',
  ashen_crow_flock: '/images/enemies/ashen_crow_flock.webp',
  ashen_guardian: '/images/enemies/ashen_guardian.webp',
  ashen_jackal: '/images/enemies/ashen_jackal.webp',
  betrayed_guardian: '/images/enemies/betrayed_guardian.webp',
  blight_alchemist: '/images/enemies/blight_alchemist.webp',
  blight_current_spawn: '/images/enemies/blight_current_spawn.webp',
  blight_mycelium_crawler: '/images/enemies/blight_mycelium_crawler.webp',
  blighted_treant: '/images/enemies/blighted_treant.webp',
  blighted_villager: '/images/enemies/blighted_villager.webp',
  blood_priest: '/images/enemies/blood_priest.webp',
  bog_wraith: '/images/enemies/bog_wraith.webp',
  bone_priest: '/images/enemies/bone_priest.webp',
  border_raider: '/images/enemies/border_raider.webp',
  broodmother_wyrm: '/images/enemies/broodmother_wyrm.webp',
  cathedral_guardian: '/images/enemies/cathedral_guardian.webp',
  cinder_stalker: '/images/enemies/cinder_stalker.webp',
  clan_scout: '/images/enemies/clan_scout.webp',
  clan_shaman: '/images/enemies/clan_shaman.webp',
  collapsed_miner: '/images/enemies/collapsed_miner.webp',
  corrupted_acolyte: '/images/enemies/corrupted_acolyte.webp',
  corrupted_treekeeper: '/images/enemies/corrupted_treekeeper.webp',
  drifting_hulk: '/images/enemies/drifting_hulk.webp',
  drowned_elf: '/images/enemies/drowned_elf.webp',
  drowned_sailor: '/images/enemies/drowned_sailor.webp',
  fallen_ruin_wraith: '/images/enemies/fallen_ruin_wraith.webp',
  feral_hatchling: '/images/enemies/feral_hatchling.webp',
  flame_wisp_swarm: '/images/enemies/flame_wisp_swarm.webp',
  forge_wraith: '/images/enemies/forge_wraith.webp',
  fortress_ash_golem: '/images/enemies/fortress_ash_golem.webp',
  fortress_warrior: '/images/enemies/fortress_warrior.webp',
  frozen_moment_wraith: '/images/enemies/frozen_moment_wraith.webp',
  fungal_stalker: '/images/enemies/fungal_stalker.webp',
  ghost_captain: '/images/enemies/ghost_captain.webp',
  gladiator_champion: '/images/enemies/gladiator_champion.webp',
  horde_captain: '/images/enemies/horde_captain.webp',
  hull_crawler: '/images/enemies/hull_crawler.webp',
  ignira_zealot: '/images/enemies/ignira_zealot.webp',
  labyrinth_stalker: '/images/enemies/labyrinth_stalker.webp',
  living_rune: '/images/enemies/living_rune.webp',
  lost_grove_soul: '/images/enemies/lost_grove_soul.webp',
  magma_elemental: '/images/enemies/magma_elemental.webp',
  marsh_zombie: '/images/enemies/marsh_zombie.webp',
  mass_grave_horror: '/images/enemies/mass_grave_horror.webp',
  mindless_flame_wisp: '/images/enemies/mindless_flame_wisp.webp',
  mirror_shard_wraith: '/images/enemies/mirror_shard_wraith.webp',
  molten_golem: '/images/enemies/molten_golem.webp',
  molten_shade: '/images/enemies/molten_shade.webp',
  mourning_wraith: '/images/enemies/mourning_wraith.webp',
  mutated_root_horror: '/images/enemies/mutated_root_horror.webp',
  nest_guardian: '/images/enemies/nest_guardian.webp',
  oathbreaker_shade: '/images/enemies/oathbreaker_shade.webp',
  obsidian_golem: '/images/enemies/obsidian_golem.webp',
  parasitic_flesh_bloom: '/images/enemies/parasitic_flesh_bloom.webp',
  petrified_sentinel: '/images/enemies/petrified_sentinel.webp',
  plague_hound: '/images/enemies/plague_hound.webp',
  possessed_guard: '/images/enemies/possessed_guard.webp',
  reality_melting_ember: '/images/enemies/reality_melting_ember.webp',
  renegade_mage: '/images/enemies/renegade_mage.webp',
  rift_collapse_horror: '/images/enemies/rift_collapse_horror.webp',
  rift_spawn: '/images/enemies/rift_spawn.webp',
  ritual_guardian: '/images/enemies/ritual_guardian.webp',
  road_bandit: '/images/enemies/road_bandit.webp',
  rock_crawler: '/images/enemies/rock_crawler.webp',
  root_horror: '/images/enemies/root_horror.webp',
  root_wraith: '/images/enemies/root_wraith.webp',
  rune_construct: '/images/enemies/rune_construct.webp',
  silt_crawler: '/images/enemies/silt_crawler.webp',
  skull_zealot: '/images/enemies/skull_zealot.webp',
  spore_horror: '/images/enemies/spore_horror.webp',
  thorn_wolf: '/images/enemies/thorn_wolf.webp',
  tornak_zealot: '/images/enemies/tornak_zealot.webp',
  toxic_experiment: '/images/enemies/toxic_experiment.webp',
  trapped_apprentice: '/images/enemies/trapped_apprentice.webp',
  tunnel_wraith: '/images/enemies/tunnel_wraith.webp',
  venom_mist_spawn: '/images/enemies/venom_mist_spawn.webp',
  war_hound: '/images/enemies/war_hound.webp',
  wasteland_marauder: '/images/enemies/wasteland_marauder.webp',
  weak_blight_spawn: '/images/enemies/weak_blight_spawn.webp',
  whispering_fear: '/images/enemies/whispering_fear.webp',
  withering_dryad: '/images/enemies/withering_dryad.webp',
};
